version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    restart: unless-stopped

  api:
    build: .
    ports:
      - "5000:5000"
    command: python api.py
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  default:
    driver: bridge
